var strVar="";
strVar += "";
strVar += "  	<div id=\"container\">";
strVar += "		<h1>HSSP CURVE<\/h1>";
strVar += "		<div id=\"description\">";
strVar += "			Visualize the HSSP curve and impose the BLAST-derived sequence alignments and allow the user to dynamically filter and export the data shown on the graph for better insights.";
strVar += "		<\/div>";
strVar += "		<br\/>";
strVar += "		";
strVar += "		<div id=\"input_wrapper\">";
strVar += "			<div class=\"row\">";
strVar += "				<div class=\"col-sm-3 nopadding\">";
strVar += "					Choose from file:";
strVar += "					<div class=\"row\">";
strVar += "						<div class=\"input-group\">";
strVar += "							<input id=\"fileToUpload\" class=\"filestyle\" type=\"file\" name=\"fileToUpload\">";
strVar += "						<\/div>";
strVar += "					<\/div>	 ";
strVar += "				<\/div>";
strVar += "				";
strVar += "				<div class=\"col-sm-1 nopadding\">				";
strVar += "				<\/div>				";
strVar += "				";
strVar += "				<div class=\"col-sm-8 nopadding\">";
strVar += "					Content:";
strVar += "					<div class=\"row\">	";
strVar += "						<div class=\"col-sm-10 nopadding\">";
strVar += "							<div class=\"input-group\">";
strVar += "								<textarea class=\"form-control\" id=\"xmlArea\" rows=\"1\" style=\"width: 100%; margin-top: 0px; margin-bottom: 0px;\"><\/textarea> ";
strVar += "							<\/div>";
strVar += "						<\/div>";
strVar += "						<div class=\"col-sm-2 nopadding\">";
strVar += "							<div class=\"input-group\">";
strVar += "								<input type=\"button\" class=\"form-control\" value=\"Clear\" onclick=\"javascript:eraseText();\"> ";
strVar += "							<\/div>";
strVar += "						<\/div>						";
strVar += "					<\/div>";
strVar += "					<div class=\"row\">	";
strVar += "						<div class=\"col-sm-4 nopadding\">";
strVar += "						<\/div>	 					";
strVar += "						<div class=\"col-sm-4 nopadding\">";
strVar += "							<div class=\"input-group\">";
strVar += "								<button class=\"form-control\" id=\"show_graph\">Extract Graph<\/button>		";
strVar += "							<\/div>";
strVar += "						<\/div>	 ";
strVar += "						<div class=\"col-sm-4 nopadding\">";
strVar += "						<\/div>	 						";
strVar += "					<\/div>";
strVar += "				<\/div>";
strVar += "				";
strVar += "				<br\/><br\/>";
strVar += "				<p style=\"display:none\">";
strVar += "				Blast Output automatically parsed into JSON:			";
strVar += "				<textarea id=\"jsonArea\" rows=\"8\"><\/textarea> ";
strVar += "				<br\/><br\/> ";
strVar += "				<\/p>";
strVar += "			<\/div>";
strVar += "		<\/div>";
strVar += "";
strVar += "		<div class=\"row\">";
strVar += "			<br\/>";
strVar += "		<\/div>";
strVar += "		";
strVar += "		<div class=\"row filter_wrapper\">";
strVar += "			<div class=\"row\">";
strVar += "				<h3>Filters<\/h3>";
strVar += "			<\/div>";
strVar += "";
strVar += "<!--";
strVar += "			<div class=\"filter\">";
strVar += "			Show >= 100% <input type=\"checkbox\" id=\"aboveOrEqualTo100\">";
strVar += "			<\/div>";
strVar += "	  		<br\/>";
strVar += "-->	  		";
strVar += "	  		<div class=\"filter\">";
strVar += "				<div class=\"row\">";
strVar += "					";
strVar += "					<div class=\"col-sm-6 nopadding\">";
strVar += "						<div class=\"row\">Filter based on HSSP score:<\/div>";
strVar += "						<div class=\"row\">";
strVar += "						<div class=\"col-sm-3\">";
strVar += "							<div class=\"input-group\">";
strVar += "								<input style=\"width: 100%;\" class=\"form-control\" type=\"text\" id=\"from\" value=\"-90\">";
strVar += "							<\/div>";
strVar += "						<\/div>";
strVar += "						<div class=\"nopadding col-sm-6\">";
strVar += "							<div id=\"slider-range\"><\/div>";
strVar += "						<\/div>";
strVar += "";
strVar += "						<div class=\"col-sm-3\">";
strVar += "							<div class=\"input-group\">";
strVar += "								<input style=\"width: 100%;\" class=\"form-control\" type=\"text\" id=\"to\" value=\"80.5\">";
strVar += "							<\/div>";
strVar += "						<\/div>";
strVar += "						<\/div>";
strVar += "					<\/div>";
strVar += "					<div class=\"col-sm-1 nopadding\">					";
strVar += "					<\/div>	";
strVar += "					<div class=\"col-sm-5 nopadding\">";
strVar += "						<div class=\"row\">HSSP-curve distance:<\/div>";
strVar += "						<div class=\"row hssp_curve_slider\">	";
strVar += "							<div class=\"col-sm-12\">		";
strVar += "								<div class=\"row\">	";
strVar += "									<input type=\"range\" name=\"hssp_curve_value\" id=\"hssp_curve_distance\" step=\"1\" value=\"0\" min=\"-19\" max=\"20\">";
strVar += "								<\/div>	";
strVar += "								<div class=\"row center\">						  	";
strVar += "									<span id=\"range_value\">53<\/span>";
strVar += "								<\/div>						  	";
strVar += "							<\/div>";
strVar += "						<\/div>";
strVar += "					<\/div>	";
strVar += "				<\/div>";
strVar += "			<\/div>";
strVar += "			<br>";
strVar += "		<\/div>";
strVar += "";
strVar += "		<div id=\"placeholder\"><\/div>";
strVar += "		<p style=\"display:none\" id=\"export\">Export:";
strVar += "			<br\/>";
strVar += "			<a href=\"javascript:void(0)\" download=\"below.txt\" id=\"below\">Download #elements below the hssp curve<\/a>";
strVar += "			<br\/>";
strVar += "			<a href=\"javascript:void(0)\" download=\"above.txt\" id=\"above\">Download #elements above the hssp curve<\/a>";
strVar += "		<\/p>";
strVar += "		<br\/>		<br\/>		<br\/>		<br\/>";
strVar += "		<div id=\"more_information\">";
strVar += "			The current implementation works with Blast output version BLASTP 2.2.29+. The input loaded here by default come from a sample output which may contain bad data so, for better understanding use your own alignment result. For generating the alignment output, you can use <a href=\"http:\/\/blast.ncbi.nlm.nih.gov\/Blast.cgi\">BLAST<\/a>.<br\/>The algorithm for calculating HSSP Curve and HSSP Values is referenced from this <a href=\"http:\/\/www.ncbi.nlm.nih.gov\/pmc\/articles\/PMC169026\/?report=classic\">paper<\/a>.<br\/>";
strVar += "			<br\/>Features:";
strVar += "			<br\/>&nbsp;&nbsp;&nbsp;&nbsp;Ability to filter based on hssp scores";
strVar += "			<br\/>&nbsp;&nbsp;&nbsp;&nbsp;Ability to zoom by selecting a part of the graph";
strVar += "			<br\/>&nbsp;&nbsp;&nbsp;&nbsp;Ability to download a screenshot of the graph or print it";
strVar += "			<br\/>&nbsp;&nbsp;&nbsp;&nbsp;Ability to download all the elements that are below or above the hssp curve in .txt format (hint: check out the pie chart)";
strVar += "			<br\/>&nbsp;&nbsp;&nbsp;&nbsp;Ability to show\/hide different data from the legend of the graph";
strVar += "			<br\/>&nbsp;&nbsp;&nbsp;&nbsp;Ability to define the distance from the hssp curve (0 being the original hssp curve)";
strVar += "		<\/div>";
strVar += "		<br\/><br\/><br\/><br\/><br\/><br\/>";
strVar += "	<\/div>";

var content = function(){};

content.html = strVar;

module.exports = content;
